---
- name: Run rhc connect command
  hosts: "{{ hostname_repos }}"
  gather_facts: false
  become: true

  tasks:
    - name: Execute rhc connect command
      ansible.builtin.command: "rhc connect --organization {{ org_id }} --activation-key {{ key }}"
      no_log: true
